name: CI Build and Push

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 550933156296
  ECR_REPO: demo_ecr_repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.build.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: (Optional) Run tests
        run: |
          echo "No tests for now"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::550933156296:role/GitHubActions-Deploy-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          ECR_URI="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}"
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
          | docker login --username AWS --password-stdin "$ECR_URI"

      - name: Build, tag, and push image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          ECR_URI="${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}"
          docker build -t "${ECR_URI}:${IMAGE_TAG}" .
          docker push "${ECR_URI}:${IMAGE_TAG}"

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT